name: Build site

on:
  push:
    branches:
      - develop

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Webhook
      run: |
        curl -X POST -d '{}' ${{ secrets.WEBHOOK_URL }}
